const contentManagementFeatures = {
  group: {
    name: 'Content',
    code: 'content',
    order: 12,
    icon: 'cilDescription',
  },
  features: [
    {
      name: 'Quan ly article',
      key: 'article.manage',
      order: 1,
      description: 'Tenant quan ly bai viet cua minh',
      path: '/articles',
      showInMenu: true,
    },
    {
      name: 'Quan ly category',
      key: 'category.manage',
      order: 2,
      description: 'Tenant quan ly category bai viet cua minh',
      path: '/categories',
      showInMenu: true,
    },
    {
      name: 'Quan ly author',
      key: 'author.manage',
      order: 3,
      description: 'Tenant quan ly tac gia bai viet cua minh',
      path: '/authors',
      showInMenu: true,
    },
    {
      name: 'Quan ly tenant config',
      key: 'tenant-config.manage',
      order: 4,
      description: 'Tenant quan ly cac cau hinh JSON cua minh',
      path: '/tenant-configs',
      showInMenu: true,
    },
    {
      name: 'Cấu hình tenant',
      key: 'tenant-setting.manage',
      order: 5,
      description: 'Quản lý các cấu hình dùng chung của tenant hiện tại',
      path: '/tenant/settings',
      showInMenu: true,
    },
    {
      name: 'Quan ly danh muc tap chi',
      key: 'journal-category.manage',
      order: 6,
      description: 'Tenant quan ly cac danh muc tap chi cua minh',
      path: '/journal-categories',
      showInMenu: true,
    },
    {
      name: 'Quan ly tap chi',
      key: 'journal-issue.manage',
      order: 7,
      description: 'Tenant quan ly cac tap chi va cac item ben trong',
      path: '/journal-issues',
      showInMenu: true,
    },
    {
      name: 'Quan ly PublicPage',
      key: 'public-page.manage',
      order: 8,
      description: 'Tenant quan ly landing page, lead page va public page cua minh',
      path: '/public-pages',
      showInMenu: true,
    },
    {
      name: 'Quan ly Frame Campaign',
      key: 'photo-frame-campaign.manage',
      order: 9,
      description: 'Tenant quan ly chien dich khung hinh cua minh',
      path: '/frame-campaigns',
      showInMenu: true,
    },
    {
      name: 'Quan ly tat ca Frame Campaign',
      key: 'photo-frame-campaign.manage.all',
      order: 10,
      description: 'Cho phep xem va quan ly toan bo frame campaign trong tenant hien tai',
      path: '/frame-campaigns',
      showInMenu: false,
    },
  ],
}

export default contentManagementFeatures