module.exports = {
  group: {
    name: 'Content',
    code: 'content',
    order: 12,
    icon: 'cilDescription',
  },
  features: [
    {
      name: 'Article Manage',
      key: 'article.manage',
      order: 1,
      description: 'Manage articles in current tenant',
      path: '/articles',
      icon: 'cilDescription',
      showInMenu: true,
    },
    {
      name: 'Category Manage',
      key: 'category.manage',
      order: 2,
      description: 'Manage article categories in current tenant',
      path: '/categories',
      icon: 'cilDescription',
      showInMenu: true,
    },
    {
      name: 'Author Manage',
      key: 'author.manage',
      order: 3,
      description: 'Manage article authors in current tenant',
      path: '/authors',
      icon: 'cilUser',
      showInMenu: true,
    },
    {
      name: 'Tenant Config Manage',
      key: 'tenant-config.manage',
      order: 4,
      description: 'Manage tenant configuration entries in current tenant',
      path: '/tenant-configs',
      icon: 'cilSettings',
      showInMenu: true,
    },
    {
      name: 'Tenant Setting Manage',
      key: 'tenant-setting.manage',
      order: 5,
      description: 'Manage tenant website settings and SEO in current tenant',
      path: '/tenant/settings/website',
      icon: 'cilSettings',
      showInMenu: true,
    },
    {
      name: 'Journal Category Manage',
      key: 'journal-category.manage',
      order: 6,
      description: 'Manage journal categories in current tenant',
      path: '/journal-categories',
      icon: 'cilDescription',
      showInMenu: true,
    },
    {
      name: 'Journal Issue Manage',
      key: 'journal-issue.manage',
      order: 7,
      description: 'Manage journal issues and issue items in current tenant',
      path: '/journal-issues',
      icon: 'cilDescription',
      showInMenu: true,
    },
    {
      name: 'Public Page Manage',
      key: 'public-page.manage',
      order: 8,
      description: 'Manage tenant public landing pages and lead pages',
      path: '/public-pages',
      icon: 'cilDescription',
      showInMenu: true,
    },
  ],
}