'use strict';

module.exports = {
  group: {
    name: 'Exam',
    code: 'exam',
    order: 21,
    icon: 'cilEducation',
  },
  features: [
    {
      name: 'Exam Round Management',
      key: 'exam-round.manage',
      order: 1,
      description: 'Create and manage tenant exam rounds from exam programs',
      path: '/exam-rounds',
      icon: 'cilEducation',
      showInMenu: true,
    },
    {
      name: 'Exam Round Approval',
      key: 'exam-round.approve',
      order: 2,
      description: 'Approve or return tenant exam rounds in approval workflow',
      path: '/exam-rounds',
      icon: 'cilCheckCircle',
      showInMenu: false,
    },
    {
      name: 'Exam Registration Self Service',
      key: 'exam-registration.self',
      order: 3,
      description: 'Allow learner self-service exam registration in tenant scope',
      path: '/exam-rounds',
      icon: 'cilUserFollow',
      showInMenu: false,
    },
    {
      name: 'Exam Payment Self Service',
      key: 'exam-payment.self',
      order: 4,
      description: 'Allow learner self-service exam payment reporting in tenant scope',
      path: '/exam-payments',
      icon: 'cilWallet',
      showInMenu: false,
    },
    {
      name: 'Exam Payment Management',
      key: 'exam-payment.manage',
      order: 5,
      description: 'Review and confirm exam payment reports in tenant scope',
      path: '/exam-payments/review',
      icon: 'cilMoney',
      showInMenu: false,
    },
    {
      name: 'Exam Registration Management',
      key: 'exam-registration.manage',
      order: 6,
      description: 'Review and accept or reject exam registrations in tenant scope',
      path: '/exam-registrations/review',
      icon: 'cilTask',
      showInMenu: false,
    },
    {
      name: 'Exam Schedule Management',
      key: 'exam-schedule.manage',
      order: 7,
      description: 'Manage exam venues, rooms, and schedules in tenant scope',
      path: '/exam-rounds/schedules',
      icon: 'cilCalendar',
      showInMenu: false,
    },
    {
      name: 'Exam Candidate Management',
      key: 'exam-candidate.manage',
      order: 8,
      description: 'Allocate candidates into schedules and manage candidate lists in tenant scope',
      path: '/exam-rounds/candidate-lists',
      icon: 'cilPeople',
      showInMenu: false,
    },
    {
      name: 'Exam Candidate Approval',
      key: 'exam-candidate.approve',
      order: 9,
      description: 'Approve and lock exam candidate lists in tenant scope',
      path: '/exam-rounds/candidate-lists',
      icon: 'cilCheckCircle',
      showInMenu: false,
    },
  ],
};