'use strict';

module.exports = {
  group: {
    name: 'COGI Sports',
    code: 'sports',
    order: 22,
    icon: 'cilChartLine',
  },
  features: [
    {
      name: 'Sports Profile Management',
      key: 'sports-profile.manage',
      order: 1,
      description: 'Manage tenant sports profiles independently from Strava integrations',
      path: '/sports/profiles',
      icon: 'cilChartLine',
      showInMenu: true,
    },
    {
      name: 'Sports Club Management',
      key: 'sports-club.manage',
      order: 2,
      description: 'Manage tenant sports clubs independently from Strava integrations',
      path: '/sports/clubs',
      icon: 'cilPeople',
      showInMenu: true,
    },
    {
      name: 'Club Membership Management',
      key: 'club-membership.manage',
      order: 3,
      description: 'Manage current sports club memberships in tenant scope',
      path: '/sports/memberships',
      icon: 'cilUserFollow',
      showInMenu: true,
    },
    {
      name: 'Sports Achievement Management',
      key: 'sports-achievement.manage',
      order: 4,
      description: 'Manage verified sports achievements in tenant scope',
      path: '/sports/achievements',
      icon: 'cilTrophy',
      showInMenu: true,
    },
    {
      name: 'Sports Achievement Submission Management',
      key: 'sports-achievement-submission.manage',
      order: 5,
      description: 'Manage sports achievement proposals and review workflow in tenant scope',
      path: '/sports/achievement-submissions',
      icon: 'cilTask',
      showInMenu: true,
    },
    {
      name: 'Sports Club Manager Assignment',
      key: 'sports-club-user-assignment.manage',
      order: 6,
      description: 'Assign tenant users to manage specific sports clubs',
      path: '/sports/club-user-assignments',
      icon: 'cilPeople',
      showInMenu: true,
    },
    {
      name: 'My Managed Clubs',
      key: 'sports-club.management',
      order: 7,
      description: 'Workspace for users assigned to manage sports clubs',
      path: '/sports/my-clubs',
      icon: 'cilListRich',
      showInMenu: true,
    },
  ],
};